-- Pattern insights generated by nightly AI analyzer
CREATE TABLE IF NOT EXISTS pattern_insights (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  hijri_year INT NOT NULL,
  hijri_month INT NOT NULL,
  hijri_day INT NOT NULL,
  cycle_day INT NOT NULL,
  week_number INT NOT NULL,
  themes TEXT[] NOT NULL,
  depth_score INT NOT NULL CHECK (depth_score BETWEEN 0 AND 100),
  shift_detected BOOLEAN DEFAULT FALSE,
  shift_description TEXT,
  daily_hint TEXT NOT NULL,
  weekly_summary TEXT,
  raw_ai_response JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, hijri_year, hijri_month, hijri_day)
);

-- RLS: each user sees only their own insights
ALTER TABLE pattern_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_own_insights" ON pattern_insights
  FOR ALL USING (auth.uid() = user_id);

-- Index for fast lookup by user + cycle day
CREATE INDEX idx_pattern_insights_user_cycle
  ON pattern_insights(user_id, cycle_day);
